export const COUNT_REQUEST = 'COUNT::REQUEST'
export const COUNT_INCREASE_SUCCESS = 'COUNT::INCREASE::SUCCESS'
export const COUNT_INCREASE_FAILURE = 'COUNT::INCREASE::FAILURE'
export const COUNT_DECREASE_SUCCESS = 'COUNT::DECREASE::SUCCESS'
export const COUNT_DECREASE_FAILURE = 'COUNT::DECREASE::FAILURE'

export const FETCH_JOBS_REQUEST = 'JOBS::FETCH::REQUEST'
export const FETCH_JOBS_SUCCESS = 'JOBS::FETCH::SUCCESS'
export const FETCH_JOBS_FAILURE = 'JOBS::FETCH::FAILURE'
