export const FETCH_POSTS_REQUEST = 'POSTS::FETCH::REQUEST'
export const FETCH_POSTS_SUCCESS = 'POSTS::FETCH::SUCCESS'
export const FETCH_POSTS_FAILURE = 'POSTS::FETCH::FAILURE'

export const SELECT_POST_REQUEST = 'POST::SELECT::REQUEST'
export const SELECT_POST_SUCCESS = 'POST::SELECT::SUCCESS'
export const SELECT_POST_FAILURE = 'POST::SELECT::FAILURE'
